# Generated by Django 5.0.3 on 2024-04-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='client',
        ),
    ]
