# Generated by Django 5.0.3 on 2024-03-28 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallonsRequested', models.PositiveIntegerField()),
                ('deliveryAddress', models.CharField(max_length=100)),
                ('deliveryDate', models.DateField()),
                ('priceQuote', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('amountDue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.client')),
            ],
        ),
        migrations.DeleteModel(
            name='fuel_quote',
        ),
    ]
