# Generated by Django 5.0.3 on 2024-03-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_fuelquote_delete_fuel_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelquote',
            old_name='deliveryAddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='fuelquote',
            old_name='deliveryDate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='fuelquote',
            old_name='amountDue',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='fuelquote',
            name='gallonsRequested',
        ),
        migrations.RemoveField(
            model_name='fuelquote',
            name='priceQuote',
        ),
        migrations.AddField(
            model_name='fuelquote',
            name='gallons',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelquote',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=20),
            preserve_default=False,
        ),
    ]
