# Generated by Django 5.0.3 on 2024-03-30 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        ('quotes', '0003_rename_deliveryaddress_fuelquote_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=30)),
                ('rate_history', models.BooleanField(default=False)),
                ('gallons', models.IntegerField(default=0)),
                ('company_profit', models.FloatField(default=0.1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.client')),
                ('fuel_quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quotes.fuelquote')),
            ],
        ),
    ]
